In [1]:
import numpy as np
import pandas as pd

frame = pd.read_excel('學生成績單.xlsx')
frame

    學號   姓名  國文   英文  數學  地理   歷史   總分    平均  排名
0    2  陳淑娟  83   96  83  89   62  413  82.6   1
1   16  劉嘉泰  92   70  87  64   89  402  80.4   2
2    5  陳向愛  88   60  92  74   86  400  80.0   3
3   13  吳淑惠  95   85  83  78   58  399  79.8   4
4    4  張天亨  90   72  74  69   93  398  79.6   5
5   17  張伊映  86   91  66  94   55  392  78.4   6
6   15  翁鈺婷  87   64  61  79  100  391  78.2   7
7    8  馮耀中  68   98  70  87   67  390  78.0   8
8   18  陳倩潔  94   82  60  71   80  387  77.4   9
9    9  劉旭士  60  100  78  86   55  379  75.8  10
10   1  劉嘉泰  80   56  78  64   97  375  75.0  11
11  20  陳俊憲  74   83  83  62   70  372  74.4  12
12   3  羅佩樺  51   66  87  68  100  372  74.4  12
13  11  張明惟  83   88  52  88   58  369  73.8  14
14   7  劉萬季  56   64  68  75  100  363  72.6  15
15  12  陳樂紫  80   86  62  63   60  351  70.2  16
16  14  陳信宏  60   86  70  77   51  344  68.8  17
17   6  吳柏誠  50   69  66  65   78  328  65.6  18
18  10  陳俊憲  53   61  68  63   73  318  63.6  19
19  19  王品星  88   54  54  60   58  314  62.8  20

In [2]:
def grade(v):
    if v >= 80:
        return '優'
    elif v >= 70:
        return '甲'
    elif v >= 60:
        return '乙'
    else:
        return '丙'


frame['等級'] = frame['平均'].map(grade)

In [3]:
frame

    學號   姓名  國文   英文  數學  地理   歷史   總分    平均  排名 等級
0    2  陳淑娟  83   96  83  89   62  413  82.6   1  優
1   16  劉嘉泰  92   70  87  64   89  402  80.4   2  優
2    5  陳向愛  88   60  92  74   86  400  80.0   3  優
3   13  吳淑惠  95   85  83  78   58  399  79.8   4  甲
4    4  張天亨  90   72  74  69   93  398  79.6   5  甲
5   17  張伊映  86   91  66  94   55  392  78.4   6  甲
6   15  翁鈺婷  87   64  61  79  100  391  78.2   7  甲
7    8  馮耀中  68   98  70  87   67  390  78.0   8  甲
8   18  陳倩潔  94   82  60  71   80  387  77.4   9  甲
9    9  劉旭士  60  100  78  86   55  379  75.8  10  甲
10   1  劉嘉泰  80   56  78  64   97  375  75.0  11  甲
11  20  陳俊憲  74   83  83  62   70  372  74.4  12  甲
12   3  羅佩樺  51   66  87  68  100  372  74.4  12  甲
13  11  張明惟  83   88  52  88   58  369  73.8  14  甲
14   7  劉萬季  56   64  68  75  100  363  72.6  15  甲
15  12  陳樂紫  80   86  62  63   60  351  70.2  16  甲
16  14  陳信宏  60   86  70  77   51  344  68.8  17  乙
17   6  吳柏誠  50   69  66  65   78  328  65.6  18  乙
18  10  陳俊憲  53   61  68  63   73  318  63.6  19  乙
19  19  王品星  88   54  54  60   58  314  62.8  20  乙

In [4]:
frame1 = frame[['國文','英文','數學','地理','歷史']]
frame1

    國文   英文  數學  地理   歷史
0   83   96  83  89   62
1   92   70  87  64   89
2   88   60  92  74   86
3   95   85  83  78   58
4   90   72  74  69   93
5   86   91  66  94   55
6   87   64  61  79  100
7   68   98  70  87   67
8   94   82  60  71   80
9   60  100  78  86   55
10  80   56  78  64   97
11  74   83  83  62   70
12  51   66  87  68  100
13  83   88  52  88   58
14  56   64  68  75  100
15  80   86  62  63   60
16  60   86  70  77   51
17  50   69  66  65   78
18  53   61  68  63   73
19  88   54  54  60   58

In [5]:
def fun1(s):    
    return s.std() #std()標準差
frame1.apply(fun1)

國文    15.535697
英文    14.587215
數學    11.447362
地理    10.556116
歷史    17.409919
dtype: float64