In [16]:
import requests
url = 'https://sheethub.com/data.gov.tw/%E5%90%84%E9%84%89%E9%8E%AE%E5%B8%82%E5%8D%80%E4%BA%BA%E5%8F%A3%E5%AF%86%E5%BA%A6?format=csv'

response = requests.request('GET',url)
if response.ok:
    print("下載成功")

下載成功

In [17]:
from io import StringIO
import csv

file = StringIO(response.text)
csv_reader = csv.reader(file)
data = list(csv_reader)
data

[['統計年', '區域別', '年底人口數', '土地面積', '人口密度'],
 ['102', '臺南市將軍區', '20808', '41.9796', '496'],
 ['102', '高雄市新興區', '53170', '1.9764', '26902'],
 ['102', '高雄市前金區', '28038', '1.8573', '15096'],
 ['102', '高雄市苓雅區', '177716', '8.1522', '21800'],
 ['102', '高雄市前鎮區', '194835', '19.1207', '10190'],
 ['102', '高雄市旗津區', '29040', '1.4639', '19837'],
 ['102', '高雄市小港區', '156115', '41.2061', '3789'],
 ['102', '高雄市鳳山區', '352574', '26.759', '13176'],
 ['102', '高雄市林園區', '70436', '32.286', '2182'],
 ['102', '高雄市大寮區', '110449', '71.04', '1555'],
 ['102', '高雄市大樹區', '43418', '66.9811', '648'],
 ['102', '高雄市大社區', '34097', '26.5848', '1283'],
 ['102', '高雄市仁武區', '79392', '36.0808', '2200'],
 ['102', '高雄市鳥松區', '43781', '24.5927', '1780'],
 ['102', '高雄市岡山區', '97800', '47.9421', '2040'],
 ['102', '高雄市橋頭區', '37010', '25.9379', '1427'],
 ['102', '高雄市燕巢區', '30542', '65.395', '467'],
 ['102', '高雄市田寮區', '7732', '92.6802', '83'],
 ['102', '高雄市阿蓮區', '29795', '34.6164', '861'],
 ['102', '高雄市路竹區', '53036', '48.4348', '1095'],
 ['102', '高雄市湖內區', '29203', '20.1615', '1448'],
 ['102', '高雄市茄萣區', '30868', '15.7624', '1958'],
 ['102', '高雄市永安區', '14138', '22.6141', '625'],
 ['102', '高雄市彌陀區', '19920', '14.7772', '1348'],
 ['102', '高雄市梓官區', '36381', '11.5967', '3137'],
 ['102', '高雄市旗山區', '38563', '94.6122', '408'],
 ['102', '高雄市美濃區', '41668', '120.0316', '347'],
 ['102', '高雄市六龜區', '13943', '194.1584', '72'],
 ['102', '高雄市甲仙區', '6444', '124.034', '52'],
 ['102', '高雄市杉林區', '12587', '104.0036', '121'],
 ['102', '高雄市內門區', '15351', '95.6224', '161'],
 ['102', '高雄市茂林區', '1832', '194', '9'],
 ['102', '高雄市桃源區', '4406', '928.98', '5'],
 ['102', '高雄市那瑪夏區', '3145', '252.9895', '12'],
 ['102', '宜蘭縣宜蘭市', '95985', '29.408', '3264'],
 ['102', '宜蘭縣羅東鎮', '72352', '11.3448', '6378'],
 ['102', '宜蘭縣蘇澳鎮', '41382', '89.0196', '465'],
 ['102', '宜蘭縣頭城鎮', '30043', '100.893', '298'],
 ['102', '宜蘭縣礁溪鄉', '35998', '101.4278', '355'],
 ['102', '宜蘭縣壯圍鄉', '24468', '38.4769', '636'],
 ['102', '宜蘭縣員山鄉', '32159', '111.9106', '287'],
 ['102', '宜蘭縣冬山鄉', '53731', '79.8573', '673'],
 ['102', '宜蘭縣五結鄉', '39230', '38.8671', '1009'],
 ['102', '宜蘭縣三星鄉', '21191', '144.2238', '147'],
 ['102', '宜蘭縣大同鄉', '6005', '657.5442', '9'],
 ['102', '宜蘭縣南澳鄉', '5912', '740.652', '8'],
 ['102', '桃園縣桃園市', '415414', '34.8046', '11936'],
 ['102', '桃園縣中壢市', '378918', '76.52', '4952'],
 ['102', '桃園縣平鎮市', '211146', '47.7532', '4422'],
 ['102', '桃園縣八德市', '179502', '33.7111', '5325'],
 ['102', '桃園縣楊梅市', '155754', '89.1229', '1748'],
 ['102', '桃園縣大溪鎮', '91961', '105.1206', '875'],
 ['102', '桃園縣蘆竹鄉', '149852', '75.5025', '1985'],
 ['102', '桃園縣大園鄉', '83586', '87.3925', '956'],
 ['102', '桃園縣龜山鄉', '140509', '72.0177', '1951'],
 ['102', '桃園縣龍潭鄉', '115728', '75.2341', '1538'],
 ['102', '桃園縣新屋鄉', '48025', '85.0166', '565'],
 ['102', '桃園縣觀音鄉', '63003', '87.9807', '716'],
 ['102', '桃園縣復興鄉', '10625', '350.7775', '30'],
 ['102', '新竹縣竹北市', '158849', '46.8341', '3392'],
 ['102', '新竹縣關西鎮', '30919', '125.5193', '246'],
 ['102', '新竹縣新埔鎮', '34674', '72.1911', '480'],
 ['102', '新竹縣竹東鎮', '96326', '53.5133', '1800'],
 ['102', '新竹縣湖口鄉', '76753', '58.4303', '1314'],
 ['102', '新竹縣橫山鄉', '13912', '66.3502', '210'],
 ['102', '新竹縣新豐鄉', '55386', '46.3496', '1195'],
 ['102', '新竹縣芎林鄉', '20256', '40.7858', '497'],
 ['102', '新竹縣寶山鄉', '14103', '64.7871', '218'],
 ['102', '新竹縣北埔鄉', '9838', '50.6676', '194'],
 ['102', '新竹縣峨眉鄉', '5764', '46.801', '123'],
 ['102', '新竹縣尖石鄉', '9167', '527.5795', '17'],
 ['102', '新竹縣五峰鄉', '4539', '227.728', '20'],
 ['102', '苗栗縣苗栗市', '91109', '37.8878', '2405'],
 ['102', '苗栗縣苑裡鎮', '48493', '68.2473', '711'],
 ['102', '苗栗縣通霄鎮', '37155', '107.8486', '345'],
 ['102', '苗栗縣竹南鎮', '82351', '37.5592', '2193'],
 ['102', '苗栗縣頭份鎮', '101527', '53.3205', '1904'],
 ['102', '苗栗縣後龍鎮', '38439', '75.8079', '507'],
 ['102', '苗栗縣卓蘭鎮', '18460', '76.3153', '242'],
 ['102', '苗栗縣大湖鄉', '15694', '90.8396', '173'],
 ['102', '苗栗縣公館鄉', '34790', '71.4523', '487'],
 ['102', '苗栗縣銅鑼鄉', '19036', '78.3805', '243'],
 ['102', '苗栗縣南庄鄉', '10742', '165.4938', '65'],
 ['102', '苗栗縣頭屋鄉', '11408', '52.5046', '217'],
 ['102', '苗栗縣三義鄉', '17411', '69.3424', '251'],
 ['102', '苗栗縣西湖鄉', '7649', '41.0758', '186'],
 ['102', '苗栗縣造橋鄉', '13517', '47.9978', '282'],
 ['102', '苗栗縣三灣鄉', '7126', '52.2964', '136'],
 ['102', '苗栗縣獅潭鄉', '4678', '79.4324', '59'],
 ['102', '苗栗縣泰安鄉', '5969', '614.5127', '10'],
 ['102', '彰化縣彰化市', '236172', '65.6947', '3595'],
 ['102', '彰化縣鹿港鎮', '85964', '39.4625', '2178'],
 ['102', '彰化縣和美鎮', '90541', '39.9345', '2267'],
 ['102', '彰化縣北斗鎮', '33151', '19.2547', '1722'],
 ['102', '彰化縣員林鎮', '124938', '40.038', '3120'],
 ['102', '彰化縣溪湖鎮', '55802', '32.0592', '1741'],
 ['102', '彰化縣田中鎮', '43106', '34.6056', '1246'],
 ['102', '彰化縣二林鎮', '52864', '92.8478', '569'],
 ['102', '彰化縣線西鄉', '17123', '18.0856', '947'],
 ['102', '彰化縣伸港鄉', '36114', '22.3268', '1618'],
 ['102', '彰化縣福興鄉', '48015', '49.8934', '962'],
 ['102', '彰化縣秀水鄉', '39385', '29.3447', '1342'],
 ['102', '彰化縣花壇鄉', '45987', '36.3469', '1265'],
 ['102', '彰化縣芬園鄉', '24258', '38.0204', '638'],
 ['102', '彰化縣大村鄉', '36452', '30.7837', '1184'],
 ['102', '彰化縣埔鹽鄉', '33456', '38.6081', '867'],
 ['102', '彰化縣埔心鄉', '35034', '20.9526', '1672'],
 ['102', '彰化縣永靖鄉', '38530', '20.6382', '1867'],
 ['102', '彰化縣社頭鄉', '43868', '36.1449', '1214'],
 ['102', '彰化縣二水鄉', '15999', '29.4449', '543'],
 ['102', '彰化縣田尾鄉', '27984', '24.0375', '1164'],
 ['102', '彰化縣埤頭鄉', '31221', '42.7508', '730'],
 ['102', '彰化縣芳苑鄉', '35104', '91.3827', '384'],
 ['102', '彰化縣大城鄉', '18043', '63.7406', '283'],
 ['102', '彰化縣竹塘鄉', '16040', '42.1662', '380'],
 ['102', '彰化縣溪州鄉', '30862', '75.831', '407'],
 ['102', '南投縣南投市', '102790', '71.6021', '1436'],
 ['102', '南投縣埔里鎮', '83701', '162.2227', '516'],
 ['102', '南投縣草屯鎮', '99297', '104.0327', '954'],
 ['102', '南投縣竹山鎮', '57101', '247.3339', '231'],
 ['102', '南投縣集集鎮', '11413', '49.7268', '230'],
 ['102', '南投縣名間鄉', '40382', '83.0955', '486'],
 ['102', '南投縣鹿谷鄉', '18667', '141.8981', '132'],
 ['102', '南投縣中寮鄉', '15719', '146.6541', '107'],
 ['102', '南投縣魚池鄉', '16696', '121.3735', '138'],
 ['102', '南投縣國姓鄉', '19919', '175.7042', '113'],
 ['102', '南投縣水里鄉', '19071', '106.8424', '178'],
 ['102', '南投縣信義鄉', '16727', '1422.4188', '12'],
 ['102', '南投縣仁愛鄉', '15739', '1273.5312', '12'],
 ['102', '雲林縣斗六市', '108011', '93.7151', '1153'],
 ['102', '雲林縣斗南鎮', '46271', '48.1505', '961'],
 ['102', '雲林縣虎尾鎮', '70486', '68.742', '1025'],
 ['102', '雲林縣西螺鎮', '47482', '49.7985', '953'],
 ['102', '雲林縣土庫鎮', '29797', '49.0212', '608'],
 ['102', '雲林縣北港鎮', '41986', '41.4999', '1012'],
 ['102', '雲林縣古坑鄉', '32865', '166.6059', '197'],
 ['102', '雲林縣大埤鄉', '20290', '44.9973', '451'],
 ['102', '雲林縣莿桐鄉', '29825', '50.8502', '587'],
 ['102', '雲林縣林內鄉', '19117', '37.6035', '508'],
 ['102', '雲林縣二崙鄉', '28712', '59.5625', '482'],
 ['102', '雲林縣崙背鄉', '26241', '58.484', '449'],
 ['102', '雲林縣麥寮鄉', '42526', '80.1668', '530'],
 ['102', '雲林縣東勢鄉', '15810', '48.3562', '327'],
 ['102', '雲林縣褒忠鄉', '13706', '37.0552', '370'],
 ['102', '雲林縣臺西鄉', '24897', '54.0983', '460'],
 ['102', '雲林縣元長鄉', '27640', '71.5872', '386'],
 ['102', '雲林縣四湖鄉', '25501', '77.1189', '331'],
 ['102', '雲林縣口湖鄉', '29344', '80.4612', '365'],
 ['102', '雲林縣水林鄉', '27285', '72.9582', '374'],
 ['102', '嘉義縣太保市', '37023', '66.8964', '553'],
 ['102', '嘉義縣朴子市', '43599', '49.5737', '879'],
 ['102', '嘉義縣布袋鎮', '28701', '61.7307', '465'],
 ['102', '嘉義縣大林鎮', '32593', '64.1663', '508'],
 ['102', '嘉義縣民雄鄉', '72096', '85.4969', '843'],
 ['102', '嘉義縣溪口鄉', '15546', '33.0463', '470'],
 ['102', '嘉義縣新港鄉', '33507', '66.0495', '507'],
 ['102', '嘉義縣六腳鄉', '24947', '62.2619', '401'],
 ['102', '嘉義縣東石鄉', '26305', '81.5821', '322'],
 ['102', '嘉義縣義竹鄉', '19856', '79.2925', '250'],
 ['102', '嘉義縣鹿草鄉', '16652', '54.3151', '307'],
 ['102', '嘉義縣水上鄉', '51289', '69.1198', '742'],
 ['102', '嘉義縣中埔鄉', '46694', '129.5016', '361'],
 ['102', '嘉義縣竹崎鄉', '37372', '162.2256', '230'],
 ['102', '嘉義縣梅山鄉', '20576', '119.7571', '172'],
 ['102', '嘉義縣番路鄉', '12174', '117.5269', '104'],
 ['102', '嘉義縣大埔鄉', '4567', '173.2472', '26'],
 ['102', '嘉義縣阿里山鄉', '5732', '427.8471', '13'],
 ['102', '屏東縣屏東市', '205945', '65.067', '3165'],
 ['102', '屏東縣潮州鎮', '55207', '42.4331', '1301'],
 ['102', '屏東縣東港鎮', '48585', '29.4635', '1649'],
 ['102', '屏東縣恆春鎮', '30823', '136.763', '225'],
 ['102', '屏東縣萬丹鄉', '52536', '57.4679', '914'],
 ['102', '屏東縣長治鄉', '30488', '39.8861', '764'],
 ['102', '屏東縣麟洛鄉', '11303', '16.26', '695'],
 ['102', '屏東縣九如鄉', '22408', '42.0187', '533'],
 ['102', '屏東縣里港鄉', '26506', '68.9208', '385'],
 ['102', '屏東縣鹽埔鄉', '26660', '64.3493', '414'],
 ['102', '屏東縣高樹鄉', '25682', '90.1522', '285'],
 ['102', '屏東縣萬巒鄉', '21164', '60.7315', '348'],
 ['102', '屏東縣內埔鄉', '56550', '81.8554', '691'],
 ['102', '屏東縣竹田鄉', '17806', '29.0732', '612'],
 ['102', '屏東縣新埤鄉', '10243', '59.0102', '174'],
 ['102', '屏東縣枋寮鄉', '25693', '57.7347', '445'],
 ['102', '屏東縣新園鄉', '37117', '38.3109', '969'],
 ['102', '屏東縣崁頂鄉', '16429', '31.2659', '525'],
 ['102', '屏東縣林邊鄉', '19573', '15.6233', '1253'],
 ['102', '屏東縣南州鄉', '11130', '18.97', '587'],
 ['102', '屏東縣佳冬鄉', '20538', '30.9842', '663'],
 ['102', '屏東縣琉球鄉', '12415', '6.8018', '1825'],
 ['102', '屏東縣車城鄉', '9106', '49.8517', '183'],
 ['102', '屏東縣滿州鄉', '8124', '142.2013', '57'],
 ['102', '屏東縣枋山鄉', '5775', '17.2697', '334'],
 ['102', '屏東縣三地門鄉', '7566', '196.3965', '39'],
 ['102', '屏東縣霧臺鄉', '3199', '278.796', '11'],
 ['102', '屏東縣瑪家鄉', '6598', '78.7008', '84'],
 ['102', '屏東縣泰武鄉', '5131', '118.6266', '43'],
 ['102', '屏東縣來義鄉', '7610', '167.7756', '45'],
 ['102', '屏東縣春日鄉', '4823', '160.001', '30'],
 ['102', '屏東縣獅子鄉', '4776', '301.0018', '16'],
 ['102', '屏東縣牡丹鄉', '4777', '181.8366', '26'],
 ['102', '臺東縣臺東市', '107316', '109.7691', '978'],
 ['102', '臺東縣成功鎮', '15051', '143.9939', '105'],
 ['102', '臺東縣關山鎮', '9268', '58.7351', '158'],
 ['102', '臺東縣卑南鄉', '17763', '412.6871', '43'],
 ['102', '臺東縣大武鄉', '6531', '69.1454', '94'],
 ['102', '臺東縣太麻里鄉', '11595', '96.6523', '120'],
 ['102', '臺東縣東河鄉', '8992', '210.1908', '43'],
 ['102', '臺東縣長濱鄉', '7733', '155.1868', '50'],
 ['102', '臺東縣鹿野鄉', '8229', '89.698', '92'],
 ['102', '臺東縣池上鄉', '8679', '82.6854', '105'],
 ['102', '臺東縣綠島鄉', '3580', '15.0919', '237'],
 ['102', '臺東縣延平鄉', '3552', '455.8805', '8'],
 ['102', '臺東縣海端鄉', '4363', '880.0382', '5'],
 ['102', '臺東縣達仁鄉', '3762', '306.4454', '12'],
 ['102', '臺東縣金峰鄉', '3502', '380.6635', '9'],
 ['102', '臺東縣蘭嶼鄉', '4905', '48.3892', '101'],
 ['102', '花蓮縣花蓮市', '107281', '29.4095', '3648'],
 ['102', '花蓮縣鳳林鎮', '11397', '120.5181', '95'],
 ['102', '花蓮縣玉里鎮', '25695', '252.3719', '102'],
 ['102', '花蓮縣新城鄉', '20148', '29.4095', '685'],
 ['102', '花蓮縣吉安鄉', '82157', '65.2582', '1259'],
 ['102', '花蓮縣壽豐鄉', '18109', '218.4448', '83'],
 ['102', '花蓮縣光復鄉', '13459', '157.11', '86'],
 ['102', '花蓮縣豐濱鄉', '4632', '162.4332', '29'],
 ['102', '花蓮縣瑞穗鄉', '12170', '135.5862', '90'],
 ['102', '花蓮縣富里鄉', '10966', '176.3705', '62'],
 ['102', '花蓮縣秀林鄉', '15267', '1641.8555', '9'],
 ['102', '花蓮縣萬榮鄉', '6495', '618.491', '11'],
 ['102', '花蓮縣卓溪鄉', '6121', '1021.313', '6'],
 ['102', '澎湖縣馬公市', '59502', '33.9918', '1750'],
 ['102', '澎湖縣湖西鄉', '14221', '33.3008', '427'],
 ['102', '澎湖縣白沙鄉', '9591', '20.0875', '477'],
 ['102', '澎湖縣西嶼鄉', '8403', '18.7148', '449'],
 ['102', '澎湖縣望安鄉', '5021', '13.7824', '364'],
 ['102', '澎湖縣七美鄉', '3662', '6.9868', '524'],
 ['102', '基隆市中正區', '53571', '10.2118', '5246'],
 ['102', '基隆市七堵區', '54041', '56.2659', '960'],
 ['102', '基隆市暖暖區', '37860', '22.8283', '1658'],
 ['102', '基隆市仁愛區', '47034', '4.2335', '11110'],
 ['102', '基隆市中山區', '49254', '10.5238', '4680'],
 ['102', '基隆市安樂區', '81906', '18.025', '4544'],
 ['102', '基隆市信義區', '51248', '10.6706', '4803'],
 ['102', '新竹市東區', '204578', '33.5768', '6093'],
 ['102', '新竹市北區', '148041', '15.7267', '9413'],
 ['102', '新竹市香山區', '75864', '54.8491', '1383'],
 ['102', '嘉義市東區', '123821', '30.1556', '4106'],
 ['102', '嘉義市西區', '147051', '29.87', '4923'],
 ['102', '金門縣金城鎮', '39062', '21.713', '1799'],
 ['102', '金門縣金湖鎮', '26074', '41.696', '625'],
 ['102', '金門縣金沙鎮', '18567', '41.19', '451'],
 ['102', '金門縣金寧鄉', '25118', '29.854', '841'],
 ['102', '金門縣烈嶼鄉', '11236', '16.003', '702'],
 ['102', '金門縣烏坵鄉', '656', '1.2', '547'],
 ['102', '連江縣南竿鄉', '7288', '10.4', '701'],
 ['102', '連江縣北竿鄉', '2268', '9.9', '229'],
 ['102', '連江縣莒光鄉', '1438', '4.7', '306'],
 ['102', '連江縣東引鄉', '1171', '3.8', '308'],
 ['102', '東沙群島', '…', '2.38', '…'],
 ['102', '南沙群島', '…', '0.4896', '…'],
 ['102', '新北市新店區', '299017', '120.2255', '2487'],
 ['102', '新北市樹林區', '183407', '33.1288', '5536'],
 ['102', '新北市鶯歌區', '88637', '21.1248', '4196'],
 ['102', '新北市三峽區', '110010', '191.4508', '575'],
 ['102', '新北市淡水區', '155241', '70.6565', '2197'],
 ['102', '新北市汐止區', '194200', '71.2354', '2726'],
 ['102', '新北市瑞芳區', '41490', '70.7336', '587'],
 ['102', '新北市土城區', '239258', '29.5578', '8095'],
 ['102', '新北市蘆洲區', '199426', '7.4351', '26822'],
 ['102', '新北市五股區', '81744', '34.8632', '2345'],
 ['102', '新北市泰山區', '77939', '19.1603', '4068'],
 ['102', '新北市林口區', '94108', '54.1519', '1738'],
 ['102', '新北市深坑區', '23622', '20.5787', '1148'],
 ['102', '新北市石碇區', '7848', '144.3498', '54'],
 ['102', '新北市坪林區', '6460', '170.835', '38'],
 ['102', '新北市三芝區', '23464', '65.9909', '356'],
 ['102', '新北市石門區', '12794', '51.2645', '250'],
 ['102', '新北市八里區', '36201', '39.4933', '917'],
 ['102', '新北市平溪區', '5002', '71.3382', '70'],
 ['102', '新北市雙溪區', '9412', '146.2484', '64'],
 ['102', '新北市貢寮區', '13306', '99.9734', '133'],
 ['102', '新北市金山區', '22392', '49.2132', '455'],
 ['102', '新北市萬里區', '22618', '63.3766', '357'],
 ['102', '新北市烏來區', '6036', '321.1306', '19'],
 ['102', '臺北市松山區', '210343', '9.2878', '22647'],
 ['102', '臺北市信義區', '228496', '11.2077', '20387'],
 ['102', '臺北市大安區', '313363', '11.3614', '27581'],
 ['102', '臺北市中山區', '228753', '13.6821', '16719'],
 ['102', '臺北市中正區', '163140', '7.6071', '21446'],
 ['102', '臺北市大同區', '129820', '5.6815', '22850'],
 ['102', '臺北市萬華區', '193480', '8.8522', '21857'],
 ['102', '臺北市文山區', '271341', '31.509', '8612'],
 ['102', '臺北市南港區', '119752', '21.8424', '5483'],
 ['102', '臺北市內湖區', '282842', '31.5787', '8957'],
 ['102', '臺北市士林區', '289742', '62.3682', '4646'],
 ['102', '臺北市北投區', '255444', '56.8216', '4496'],
 ['102', '臺中市中區', '20008', '0.8803', '22729'],
 ['102', '臺中市東區', '74572', '9.2855', '8031'],
 ['102', '臺中市南區', '118349', '6.8101', '17378'],
 ['102', '臺中市西區', '116397', '5.7042', '20405'],
 ['102', '臺中市北區', '147880', '6.9376', '21316'],
 ['102', '臺中市西屯區', '215485', '39.8467', '5408'],
 ['102', '臺中市南屯區', '159952', '31.2578', '5117'],
 ['102', '臺中市北屯區', '255978', '62.7034', '4082'],
 ['102', '臺中市豐原區', '166090', '41.1845', '4033'],
 ['102', '臺中市東勢區', '51953', '117.4065', '443'],
 ['102', '臺中市大甲區', '77847', '58.5192', '1330'],
 ['102', '臺中市清水區', '86061', '64.1709', '1341'],
 ['102', '臺中市沙鹿區', '86305', '40.4604', '2133'],
 ['102', '臺中市梧棲區', '56008', '16.6049', '3373'],
 ['102', '臺中市后里區', '54076', '58.9439', '917'],
 ['102', '臺中市神岡區', '64899', '35.0445', '1852'],
 ['102', '臺中市潭子區', '104471', '25.8497', '4041'],
 ['102', '臺中市大雅區', '91939', '32.4109', '2837'],
 ['102', '臺中市新社區', '25322', '68.8874', '368'],
 ['102', '臺中市石岡區', '15636', '18.2105', '859'],
 ['102', '臺中市外埔區', '31845', '42.4099', '751'],
 ['102', '臺中市大安區', '19720', '27.4045', '720'],
 ['102', '臺中市烏日區', '70624', '43.4032', '1627'],
 ['102', '臺中市大肚區', '55995', '37.0024', '1513'],
 ['102', '臺中市龍井區', '75664', '38.0377', '1989'],
 ['102', '臺中市霧峰區', '64280', '98.0779', '655'],
 ['102', '臺中市太平區', '178870', '120.7473', '1481'],
 ['102', '臺中市大里區', '204846', '28.8758', '7094'],
 ['102', '臺中市和平區', '10589', '1037.8192', '10'],
 ['102', '臺南市新營區', '78521', '38.5386', '2037'],
 ['102', '臺南市鹽水區', '26426', '52.2455', '506'],
 ['102', '臺南市白河區', '30178', '126.4046', '239'],
 ['102', '臺南市柳營區', '21932', '61.2929', '358'],
 ['102', '臺南市後壁區', '24910', '72.2189', '345'],
 ['102', '臺南市東山區', '22195', '124.9178', '178'],
 ['102', '臺南市麻豆區', '45230', '53.9744', '838'],
 ['102', '臺南市下營區', '25333', '33.5291', '756'],
 ['102', '臺南市六甲區', '23151', '67.5471', '343'],
 ['102', '臺南市官田區', '21823', '70.7953', '308'],
 ['102', '臺南市大內區', '10408', '70.3125', '148'],
 ['102', '臺南市佳里區', '59372', '38.9422', '1525'],
 ['102', '臺南市學甲區', '27167', '53.9919', '503'],
 ['102', '臺南市西港區', '24914', '33.7666', '738'],
 ['102', '臺南市七股區', '23871', '110.1492', '217'],
 ['102', '臺南市北門區', '11876', '44.1003', '269'],
 ['102', '臺南市新化區', '43836', '62.0579', '706'],
 ['102', '臺南市善化區', '45167', '55.3097', '817'],
 ['102', '臺南市新市區', '35336', '47.8096', '739'],
 ['102', '臺南市安定區', '30215', '31.27', '966'],
 ['102', '臺南市山上區', '7570', '27.878', '272'],
 ['102', '臺南市玉井區', '14821', '76.3662', '194'],
 ['102', '臺南市楠西區', '10186', '109.6316', '93'],
 ['102', '臺南市南化區', '8894', '171.5198', '52'],
 ['102', '臺南市左鎮區', '5211', '74.9025', '70'],
 ['102', '臺南市仁德區', '72444', '50.7664', '1427'],
 ['102', '臺南市歸仁區', '67101', '55.7913', '1203'],
 ['102', '臺南市關廟區', '35105', '53.6413', '654'],
 ['102', '臺南市龍崎區', '4310', '64.0814', '67'],
 ['102', '臺南市永康區', '226875', '40.2753', '5633'],
 ['102', '臺南市東區', '191576', '13.4156', '14280'],
 ['102', '臺南市南區', '125611', '27.2681', '4607'],
 ['102', '臺南市北區', '132336', '10.434', '12683'],
 ['102', '臺南市安南區', '185412', '107.2016', '1730'],
 ['102', '臺南市安平區', '64589', '11.0663', '5837'],
 ['102', '臺南市中西區', '78498', '6.26', '12540'],
 ['102', '高雄市鹽埕區', '25847', '1.4161', '18252'],
 ['102', '高雄市鼓山區', '135102', '14.7458', '9162'],
 ['102', '高雄市左營區', '195436', '19.3888', '10080'],
 ['102', '高雄市楠梓區', '177579', '25.8276', '6876'],
 ['102', '高雄市三民區', '348488', '19.7866', '17612'],
 ['102', '新北市板橋區', '556920', '23.1373', '24070'],
 ['102', '新北市三重區', '389813', '16.317', '23890'],
 ['102', '新北市中和區', '415742', '20.144', '20639'],
 ['102', '新北市永和區', '229062', '5.7138', '40089'],
 ['102', '新北市新莊區', '409760', '19.7383', '20760']]

In [18]:
import pandas as pd

frame = pd.DataFrame(data)
frame

       0       1       2        3      4
0    統計年     區域別   年底人口數     土地面積   人口密度
1    102  臺南市將軍區   20808  41.9796    496
2    102  高雄市新興區   53170   1.9764  26902
3    102  高雄市前金區   28038   1.8573  15096
4    102  高雄市苓雅區  177716   8.1522  21800
..   ...     ...     ...      ...    ...
366  102  新北市板橋區  556920  23.1373  24070
367  102  新北市三重區  389813   16.317  23890
368  102  新北市中和區  415742   20.144  20639
369  102  新北市永和區  229062   5.7138  40089
370  102  新北市新莊區  409760  19.7383  20760

[371 rows x 5 columns]

In [19]:
frame.columns = frame.iloc[0]
frame1 = frame.drop(index=0)
frame1

0    統計年     區域別   年底人口數     土地面積   人口密度
1    102  臺南市將軍區   20808  41.9796    496
2    102  高雄市新興區   53170   1.9764  26902
3    102  高雄市前金區   28038   1.8573  15096
4    102  高雄市苓雅區  177716   8.1522  21800
5    102  高雄市前鎮區  194835  19.1207  10190
..   ...     ...     ...      ...    ...
366  102  新北市板橋區  556920  23.1373  24070
367  102  新北市三重區  389813   16.317  23890
368  102  新北市中和區  415742   20.144  20639
369  102  新北市永和區  229062   5.7138  40089
370  102  新北市新莊區  409760  19.7383  20760

[370 rows x 5 columns]

In [20]:
frame1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 14.6+ KB

In [21]:
frame1.index = frame1['區域別']
frame1[['年底人口數','土地面積','人口密度']]

0        年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190
...        ...      ...    ...
新北市板橋區  556920  23.1373  24070
新北市三重區  389813   16.317  23890
新北市中和區  415742   20.144  20639
新北市永和區  229062   5.7138  40089
新北市新莊區  409760  19.7383  20760

[370 rows x 3 columns]

In [22]:
frame2 = frame1.reindex(columns=['年底人口數','土地面積','人口密度'])
frame2

0        年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190
...        ...      ...    ...
新北市板橋區  556920  23.1373  24070
新北市三重區  389813   16.317  23890
新北市中和區  415742   20.144  20639
新北市永和區  229062   5.7138  40089
新北市新莊區  409760  19.7383  20760

[370 rows x 3 columns]

In [23]:
frame2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 臺南市將軍區 to 新北市新莊區
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   370 non-null    object
 1   土地面積    370 non-null    object
 2   人口密度    370 non-null    object
dtypes: object(3)
memory usage: 11.6+ KB

In [24]:
frame2[frame2['年底人口數'] == "…"]

0    年底人口數    土地面積 人口密度
區域別
東沙群島     …    2.38    …
南沙群島     …  0.4896    …

In [25]:
frame3 = frame2.drop(index=['東沙群島','南沙群島'])
frame3

0        年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190
...        ...      ...    ...
新北市板橋區  556920  23.1373  24070
新北市三重區  389813   16.317  23890
新北市中和區  415742   20.144  20639
新北市永和區  229062   5.7138  40089
新北市新莊區  409760  19.7383  20760

[368 rows x 3 columns]

In [27]:
frame3['年底人口數'] = frame3['年底人口數'].astype(int)
frame3['土地面積'] = frame3['土地面積'].astype(float)
frame3['人口密度'] = frame3['人口密度'].astype(int)
display(frame3)
frame3.info()

0        年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190
...        ...      ...    ...
新北市板橋區  556920  23.1373  24070
新北市三重區  389813  16.3170  23890
新北市中和區  415742  20.1440  20639
新北市永和區  229062   5.7138  40089
新北市新莊區  409760  19.7383  20760

[368 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
Index: 368 entries, 臺南市將軍區 to 新北市新莊區
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   368 non-null    int64
 1   土地面積    368 non-null    float64
 2   人口密度    368 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 11.5+ KB